### ISSUE TITLE
회원가입 API

### ISSUE THREAD

**Issue by kook-extended** [codestates/cinephile_server#3]
##Task Card

**Description**

회원 가입 API 입니다
이메일과 비밀번호, 닉네임을 입력받습니다
(성별, 나이) <<< advanced

**TO DO**

- [x] 사용자의 정보 입력
- [x] 입력된 정보 중 이메일, 닉네임 중복체크
- [x] 패스워드 체크 
- [x] 정보가 잘 입력되었다면 DB에 유저정보 생성

**Estimated Time**

2H

**Additional context**

성별과 나이는 advanced 과제입니다!!!!
